name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SECOND_POC_TOKEN }}

      - name: Verify remote URL
        run: git remote -v

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '18.20.2'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Get the current tag
        id: get_tag
        shell: powershell
        run: |
          $tag = git tag --list --sort=-v:refname | Select-Object -First 1
          if (-not $tag) { $tag = "v0.0.0" }
          echo "::set-output name=tag::$tag"

      - name: Bump version
        id: bump_version
        shell: powershell
        run: |
          function Increment-Version {
              param(
                  [string]$version
              )
              $version_parts = $version.TrimStart('v').Split('.')
              $major = [int]$version_parts[0]
              $minor = [int]$version_parts[1]
              $patch = [int]$version_parts[2]
              $patch++
              return "v$major.$minor.$patch"
          }

          $current_tag = '${{ steps.get_tag.outputs.tag }}'
          $new_tag = Increment-Version -version $current_tag

          # Ensure the new tag does not already exist
          while (git tag --list | Select-String -Pattern $new_tag) {
              $new_tag = Increment-Version -version $new_tag
          }

          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Tag build
        shell: powershell
        run: git tag -a ${{ steps.bump_version.outputs.new_tag }} -m "Version ${{ steps.bump_version.outputs.new_tag }}"

      - name: Push tags
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.SECOND_POC_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/mandy8055/demo-cicd-poc.git
          git push origin --tags

      - name: Upload build artifacts to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name storagetp2 --source ./dist --destination 'ui-tp2'
          azcliversion: 2.0.72
