name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SECOND_POC_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '18.20.2'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: |
          npm run build

      - name: Version bump and tag
        run: .\scripts\version_bump.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.SECOND_POC_TOKEN }}

      - name: Set Release Version for tagging artefact
        id: set_version
        run: |
          $releaseVersion = "v" + (Get-Date -Format "yyyyMMddHHmmss")
          echo "RELEASE_VERSION=$releaseVersion" >> $env:GITHUB_ENV

      - name: Upload build artifacts to Azure Storage
        run: |
          az login --identity
          az storage blob upload-batch --account-name storagetp2 --source ./dist --destination 'ui-tp2/${{ env.RELEASE_VERSION }}'
